-- Magnitude Analysis
-- measures - quantity, price, sales_amount
-- dimensions - products, customers
-- comparing measure values by categories
-- understand the importances of each category.

-- 1. Total customer by countries
SELECT 
	country,
    count(customer_key) AS total_customer
FROM dw_gold.dim_customers
GROUP BY country;

-- 2. Find total customers by gender
SELECT 
	Gender,
    count(Gender) AS count
FROM dw_gold.dim_customers
GROUP BY Gender;

-- 3. Total products by category
SELECT category, count(product_key) AS count
FROM dw_gold.dim_products
GROUP BY category;

-- 4. The average revenues for each category
SELECT 
	p.category AS category,
    AVG(s.sales_amount) AS Average_revenue
	
FROM dw_gold.facts_sales s
LEFT JOIN dw_gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category;

-- 5. The total revenues generated by each category
SELECT 
	p.category AS category,
    SUM(s.sales_amount) AS total_revenue
	
FROM dw_gold.facts_sales s
LEFT JOIN dw_gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category;

-- 6. Distribution of sold items across the regions.
SELECT 
	c.country AS country,
    count(c.customer_key) AS country_count
FROM dw_gold.facts_sales s
JOIN dw_gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY c.country;

-- 7. What is the distribution of sold items across countries
SELECT 
	c.country AS country,
    count(s.customer_key) AS count_num
FROM dw_gold.facts_sales s 
LEFT JOIN dw_gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country;

-- RANKING ANALYSIS
-- Rank Dimension by aggregate measure
-- Which 5 Products generate the highest revenue
SELECT 
	Rank() OVER (ORDER BY SUM(s.sales_amount) DESC) AS position,
	p.product_name AS product_name,
    count(p.product_name) As count,
    SUM(s.sales_amount) AS total_revenue
	
FROM dw_gold.facts_sales s
LEFT JOIN dw_gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY SUM(s.sales_amount) DESC
LIMIT 5;



-- What are the 5 worst performing products in terms of sales
SELECT 
	Rank() OVER (ORDER BY SUM(s.sales_amount) DESC) AS position,
	p.product_name AS product_name,
    count(p.product_name) As count,
    SUM(s.sales_amount) AS total_revenue
	
FROM dw_gold.facts_sales s
LEFT JOIN dw_gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY SUM(s.sales_amount) 
LIMIT 5;
